Initial checkin for Horizon Intra-Company Sharing Quickstart
Snowflake-Labs/sfquickstarts pull request #1279
Opened 2024-05-21 19:55 UTC by sfc-gh-vsrihari

Initial checkin for this quickstart and summit lab hands-on-lab

2024-05-21 20:12 UTC, iamontheinet requested changes

2024-05-21 20:12 UTC, iamontheinet commented on site/sfguides/src/horizon_intra_org_sharing/horizon_intra_org_sharing.md
> +<!--- Categories below should be hyphenated, i.e., Getting-Started. Do not leave blank. Visit site for available categories. -->
@sfc-gh-vsrihari Pl delete this comment.

2024-05-21 20:12 UTC, iamontheinet commented on site/sfguides/src/horizon_intra_org_sharing/horizon_intra_org_sharing.md
> +categories: horizon-access,data-sharing,summit-hol
@sfc-gh-vsrihari See https://quickstarts.snowflake.com/ for valid categories

2024-05-21 20:12 UTC, iamontheinet commented on site/sfguides/src/horizon_intra_org_sharing/horizon_intra_org_sharing.md
> +## Conclusion
@sfc-gh-vsrihari Make the layout and structure of this section similar to https://quickstarts.snowflake.com/guide/getting_started_with_dataengineering_ml_using_snowpark_python/index.html#8

2024-05-22 16:11 UTC, sfc-gh-vsrihari commented on site/sfguides/src/horizon_intra_org_sharing/horizon_intra_org_sharing.md
> +<!--- Categories below should be hyphenated, i.e., Getting-Started. Do not leave blank. Visit site for available categories. -->
Done.

2024-05-22 16:11 UTC, sfc-gh-vsrihari commented on site/sfguides/src/horizon_intra_org_sharing/horizon_intra_org_sharing.md
> +categories: horizon-access,data-sharing,summit-hol
Added Data-Sharing. Can we add these to the list of categories in Quickstart, please?

2024-05-22 16:11 UTC, sfc-gh-vsrihari commented on site/sfguides/src/horizon_intra_org_sharing/horizon_intra_org_sharing.md
> +## Conclusion
Done.

2024-05-22 21:55 UTC, closed without merging