Merge patterns
Snowflake-Labs/sfquickstarts pull request #14
Opened 2020-12-23 21:22 UTC by sfc-gh-dturnbull

Merge patterns from the Partner CTO/Partner SE team.

2021-01-22 20:24 UTC, jdanielmyers commented on site/devlabs/security_authentication_pattern.md
> +sign-on, while others don\'t.
remove the /

2021-01-22 20:25 UTC, jdanielmyers commented on site/devlabs/security_authentication_pattern.md
> +### WHEN TO USE THESE PATTERNS
please make all step titles, regular title cased.

2021-02-23 13:17 UTC, sfc-gh-dturnbull commented
Updated in line with guidance

2021-03-01 23:02 UTC, jdanielmyers requested changes
This is looking good! -- there are some typos, broken links, and many backslashes (looks like someone was trying to escape special characters, but that is not needed here).

2021-03-01 23:02 UTC, jdanielmyers commented on site/devlabs/security_authentication_pattern.md
> +Snowflake's \"External Browser\" mode on the desktop. When a desktop
please remove the backslashes. 

```suggestion
Snowflake's "External Browser" mode on the desktop. When a desktop
```

2021-03-01 23:02 UTC, jdanielmyers commented on site/devlabs/security_authentication_pattern.md
> +\
Please remove back slashes

2021-03-01 23:02 UTC, jdanielmyers commented on site/devlabs/security_authentication_pattern.md
> +1.  At the time of this writing, SAML-based SSO can only be used on
Please put the date instead of "at the time of writing" -- readers don't know when this was written. Please make this change everywhere it says "at the time of writing"

2021-03-01 23:02 UTC, jdanielmyers commented on site/devlabs/security_authentication_pattern.md
> +\
backslashes

2021-03-01 23:02 UTC, jdanielmyers commented on site/devlabs/security_authentication_pattern.md
> +3.  Snowflake allows for the aggressive rotation of key pairs.  \
more slashes

2021-03-01 23:02 UTC, jdanielmyers commented on site/devlabs/security_access_to_sensitive_objects.md
> +        tables in both the PUBLIC and SENSITIVE schemas.  
all of the slashes here need to be removed and the role names need to be in inline code format 

i.e. `PROD_DB_RO`

2021-03-01 23:02 UTC, jdanielmyers commented on site/devlabs/security_network_architecture_pattern.md
> +documentation(https://docs.snowflake.com/en/user-guide/network-policies.html&sa=D&ust=1608660555636000&usg=AOvVaw0fln45ribJ65YZRAZd3B09).
this link is broken

2021-03-01 23:02 UTC, jdanielmyers commented on site/devlabs/security_network_architecture_pattern.md
> + - [Setup Considerations When Integrating AWS PrivateLink with Snowflake](https://community.snowflake.com/s/article/Setup-Considerations-When-Integrating-AW S-PrivateLink-With-Snowflake&sa=D&ust=1608
link is broken

2021-03-01 23:02 UTC, jdanielmyers commented on site/devlabs/security_network_architecture_pattern.md
> + - [HOWTO: Block a Specific IP in Snowflake](https://community.snowflake.com/s/article/How-to-block-a-specific-IP-address-using-Network-Policies-in-Snowflake&sa=D& ust=1608660555643000&usg=AOvVaw1d H
link is broken

2021-03-23 02:12 UTC, merged