Data Engineering with Snowpark Pandas API QuickStart
Snowflake-Labs/sfquickstarts pull request #1417
Opened 2024-07-03 17:46 UTC by sfc-gh-mstellwall

New Quickstart for doing Data Engineering with Snowpark Pandas API.

2024-07-03 20:32 UTC, sfc-gh-dolee requested changes

2024-07-03 20:32 UTC, sfc-gh-dolee commented on site/sfguides/src/data_engineering_piipelines_with_snowpark_pandas/data_engineering_pipelines_with_snowpark_pandas.md
> +You can also use the git integration feature of Snowflake Notebooks, in order to do that you need to fork the [GitHub repository](https://github.com/Snowflake-Labs/sfguide-data-engineering-pipelines-
```suggestion
You can also use the Git integration feature of Snowflake Notebooks, in order to do that you need to fork the [GitHub repository](https://github.com/Snowflake-Labs/sfguide-data-engineering-pipelines-with-snowpark-pandas) to be allowed to commit changes. For instructions how to set up Git integration for your Snowflake account see [here](https://docs.snowflake.com/developer-guide/git/git-setting-up) and for using it with Snowflake Notebooks see [this page](https://docs.snowflake.com/en/user-guide/ui-snowsight/notebooks-snowgit).
```

2024-07-03 20:32 UTC, sfc-gh-dolee commented on site/sfguides/src/data_engineering_piipelines_with_snowpark_pandas/data_engineering_pipelines_with_snowpark_pandas.md
> +The notebook is depending on the following Python libraries:
```suggestion
Before you run the notebook you need to add the following Python libraries:
```

2024-07-03 20:32 UTC, sfc-gh-dolee commented on site/sfguides/src/data_engineering_piipelines_with_snowpark_pandas/data_engineering_pipelines_with_snowpark_pandas.md
> +* snowflake-snowpark-python (version 1.17 or higher)
```suggestion
```

2024-07-03 20:32 UTC, sfc-gh-dolee commented on site/sfguides/src/data_engineering_piipelines_with_snowpark_pandas/data_engineering_pipelines_with_snowpark_pandas.md
> +* snowflake-snowpark-python (version 1.17 or higher)
Removed since Snowpark comes pre-installed with every notebook.

2024-07-03 20:32 UTC, sfc-gh-dolee commented on site/sfguides/src/data_engineering_piipelines_with_snowpark_pandas/data_engineering_pipelines_with_snowpark_pandas.md
> +During this step you will learn how to use the Snowpark Pandas API to
```suggestion
During this step you will learn how to use the Snowpark Pandas API to:
```

2024-07-03 20:32 UTC, sfc-gh-dolee commented on site/sfguides/src/data_engineering_piipelines_with_snowpark_pandas/data_engineering_pipelines_with_snowpark_pandas.md
> +* Create a serverless task to schedule the feature engineering
```suggestion
* Create a serverless task to schedule the feature engineering pipeline (Currently in Private Preview)
```

2024-07-03 20:32 UTC, sfc-gh-dolee commented on site/sfguides/src/data_engineering_piipelines_with_snowpark_pandas/data_engineering_pipelines_with_snowpark_pandas.md
> +Run each of the cells in the Notebook.
```suggestion
Follow along and run each of the cells in [the Notebook](https://github.com/Snowflake-Labs/sfguide-data-engineering-pipelines-with-snowpark-pandas/blob/main/Customer%20Profile%20Creation%20Pipeline.ipynb).
```

2024-07-03 20:32 UTC, sfc-gh-dolee commented on site/sfguides/src/data_engineering_piipelines_with_snowpark_pandas/data_engineering_pipelines_with_snowpark_pandas.md
> +Congratulations, you have successfully completed this quickstart! Through this quickstart, we were able to showcase how you can use the Snowpark Pandas API to create DataFrames, join them, create new
```suggestion
Congratulations, you have successfully completed this quickstart! Through this quickstart, we were able to showcase how you can use the Snowpark Pandas API to create DataFrames, join them, create new features, save the result to a Snowflake table, and create a serverless task to schedule the data transformation pipeline.
```

2024-07-03 20:32 UTC, sfc-gh-dolee commented on site/sfguides/src/data_engineering_piipelines_with_snowpark_pandas/data_engineering_pipelines_with_snowpark_pandas.md
> +* [Getting Started with Snowpark pandas QuikStart](https://quickstarts.snowflake.com/guide/getting_started_with_snowpark_pandas/index.html)
```suggestion
* [Getting Started with Snowpark pandas Quickstart](https://quickstarts.snowflake.com/guide/getting_started_with_snowpark_pandas/index.html)
```

2024-07-03 20:53 UTC, sfc-gh-dolee requested changes

2024-07-03 20:53 UTC, sfc-gh-dolee commented on site/sfguides/src/data_engineering_piipelines_with_snowpark_pandas/data_engineering_pipelines_with_snowpark_pandas.md
> +# Snowpark Pandas API Data Pipeline
```suggestion
# Data Engineering Pipeline with Snowpark Pandas
```

2024-07-03 20:56 UTC, sfc-gh-dolee commented
Looks good overall! Some minor comments in the review above. 
- It looks like the draft of another quickstart was merged in. Is this intentional? 
- In addition, could you rename the folder from `site/sfguides/src/data_engineering_piipelines_with_snowpark_pandas` to site/sfguides/src/data_engineering_pipelines_with_snowpark_pandas`? 
Thanks!

2024-07-04 09:44 UTC, sfc-gh-mstellwall commented
@sfc-gh-dolee it should all be fixed now.
@iamontheinet Would it be possible for you to merge this? 
It is a new qucikstart for Snowpark Pandas.
Many thanks!

2024-07-09 02:37 UTC, iamontheinet requested changes

2024-07-09 02:37 UTC, iamontheinet commented on site/sfguides/src/deploying_custom_models_to_snowpark_model_registry/deploying_custom_models_to_snowpark_model_registry.md
> +<!--- Categories below should be hyphenated, i.e., Getting-Started. Do not leave blank. Visit site for available categories. -->
@sfc-gh-mstellwall Please delete this comment and don't leave a blank line between the attritbutes afterwards.

2024-07-09 02:37 UTC, iamontheinet commented on site/sfguides/src/deploying_custom_models_to_snowpark_model_registry/deploying_custom_models_to_snowpark_model_registry.md
> +status: Draft
@sfc-gh-mstellwall Is it still in Draft mode? If not, change this to Published for it to be deployed.

2024-07-09 02:37 UTC, iamontheinet commented on site/sfguides/src/deploying_custom_models_to_snowpark_model_registry/deploying_custom_models_to_snowpark_model_registry.md
> +## Conclusion
@sfc-gh-mstellwall Change this step label to "Conclusion And Resources"

2024-07-12 08:44 UTC, closed without merging