Adding Amperity Quickstart
Snowflake-Labs/sfquickstarts pull request #1607
Opened 2024-09-25 18:13 UTC by djperlovsky

Adding quickstart + assets for Building a Unified Customer 360 using Snowflake + Amperity. Followed all instructions in [the guide](https://github.com/Snowflake-Labs/sfquickstarts?tab=readme-ov-file#snowflake-quickstart-guides)

I validated the changes locally -> only note is that the assets I added didn't show up in localhost. I assume that is an environment thing. All links work + styling looks correct. 
![image](https://github.com/user-attachments/assets/d3254f34-59c7-4aea-868a-a151361f8fe6)

Per the instructions, I accept the Contributor License Agreement

Let me know if you have any questions or concerns

2024-10-04 00:22 UTC, iamontheinet requested changes

2024-10-04 00:22 UTC, iamontheinet commented on site/sfguides/src/build-unified-customer-360-using-amperity/build-unified-customer-360-using-amperity.md
> +tags: Getting Started, Data Science, Data Engineering, Twitter
@djperlovsky Remove tags that don't apply to this QS.

2024-10-04 00:22 UTC, iamontheinet commented on site/sfguides/src/build-unified-customer-360-using-amperity/build-unified-customer-360-using-amperity.md
> +# Build a Unified Customer 360 Database using Amperity
@djperlovsky Add "and Snowflake" at the end of the title.

2024-10-04 00:22 UTC, iamontheinet commented on site/sfguides/src/build-unified-customer-360-using-amperity/build-unified-customer-360-using-amperity.md
> +- Access to a Snowflake account with the ability to set up secure data sharing
@djperlovsky Add link to Snowflake signin/signup page.

2024-10-04 22:02 UTC, djperlovsky commented
@iamontheinet Responded to the feedback and uploaded new changes. Any other feedback or am I good to merge?

2024-10-08 16:05 UTC, djperlovsky commented
@iamontheinet @sfc-gh-lambrosetti Can I get some eyes here?

2024-10-10 17:05 UTC, sfc-gh-lambrosetti commented
@iamontheinet - this looks good to me. images didn't load locally because of the typical issue there, but otherwise, everything else looks great!

2024-10-10 17:09 UTC, merged