Snowflake Native App Quickstart v2
Snowflake-Labs/sfquickstarts pull request #1681
Opened 2024-10-23 20:52 UTC by danhlee

Updated steps and images to reflect latest changes to native app setup and and run procedures

2024-12-10 16:23 UTC, iamontheinet requested changes

2024-12-10 16:23 UTC, iamontheinet commented on site/sfguides/src/how_to_resolve_data_with_fullcontact_and_snowflake/how_to_resolve_data_with_fullcontact_and_snowflake.md
> +author: cxteam@fullcontact.com
@danhlee Remove your email and add your name.

2024-12-10 16:23 UTC, iamontheinet commented on site/sfguides/src/how_to_resolve_data_with_fullcontact_and_snowflake/how_to_resolve_data_with_fullcontact_and_snowflake.md
@danhlee Rename the last step to "Conclusion And Resources" and make the layout/format similar to https://quickstarts.snowflake.com/guide/getting_started_with_snowflake_arctic/index.html#5

2024-12-19 01:00 UTC, danhlee commented
@iamontheinet requested changes have been made. Let me know if you need anything else. Thanks!

2024-12-20 23:08 UTC, merged