dbt Labs' Snowflake Summit Quickstart leveraging ml pipelines -- attempt to resolve package-lock.json
Snowflake-Labs/sfquickstarts pull request #679
Opened 2023-05-25 14:11 UTC by HopeMWatson

This PR is for a new quickstart for snowflake summit for dbt Labs' hands on session using snowpark for python and dbt python. 

There appears to be a merge conflict stemming from the package-lock.json file. This was unaltered during forking and the file has not been altered for 7 months. It was most recently altered by my dbt Labs' colleague Bobby and appears he had a similar issue with updating another quickstart. 

I attempted to solve previous package-lock.json file issues by:
1. deleting it upon Ripu's (snowflake team) request
2. recreateing attempting to use the package-lock.json that is currently in `main` of the Snowflake-Lab/sfquickstarts that should be up-to-date.
3. git pull the main using the method [here](https://gist.github.com/szemate/6fb69c8e3d8cce3efa9a6c922b337d98) 

<img width="710" alt="Screenshot 2023-05-25 at 9 08 16 AM" src="https://github.com/Snowflake-Labs/sfquickstarts/assets/40265898/53c6f3ed-df96-46ee-840a-c688308e7837">

<img width="737" alt="Screenshot 2023-05-25 at 9 52 13 AM" src="https://github.com/Snowflake-Labs/sfquickstarts/assets/40265898/76a61a20-4b01-47d6-94cb-dfa40ef84b92">

2023-05-26 13:49 UTC, iamontheinet requested changes
@HopeMWatson Hi Hope! The duration at the Overview starts off at "3 mins remaining" and then on every subsequent step it's "0 mins remaining" -- can you please fix that? Thanks!

2023-05-30 12:08 UTC, amychen1776 commented on site/sfguides/src/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python.md
> +## IDE overview and buidling first dbt models
```suggestion
## IDE overview and buidling first dbt models
Duration: 2
```

2023-05-30 12:09 UTC, amychen1776 commented on site/sfguides/src/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python.md
> +## Understanding our existing pipeline
```suggestion
## Understanding our existing pipeline 
Duration: 2
```

2023-05-30 12:09 UTC, amychen1776 commented on site/sfguides/src/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python.md
> +## SQL Transformations
```suggestion
## SQL Transformations 
Duration: 5
```

2023-05-30 12:10 UTC, amychen1776 commented on site/sfguides/src/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python.md
> +## Python development in snowflake python worksheets
```suggestion
## Python development in snowflake python worksheets 
Duration: 5
```

2023-05-30 12:11 UTC, amychen1776 commented on site/sfguides/src/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python.md
> +<!-- TODO I think more explanation of python worksheets would go well here. (@snowflake team)(@Dan)(@Ripu)
```suggestion
```

2023-05-30 12:11 UTC, amychen1776 commented on site/sfguides/src/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python.md
> +I did this but if you want it updated, feel free to-->
```suggestion
```

2023-05-30 12:11 UTC, amychen1776 commented on site/sfguides/src/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python.md
> +<!-- TODO (@snowflake team)(@Dan) -- feel free to translate this python worksheet into snowpark code and clean up a bit (i.e. final_df isn't really necessary) -->
```suggestion
```

2023-05-30 12:12 UTC, amychen1776 commented on site/sfguides/src/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python.md
> +## Python transfomrations in dbt Cloud
```suggestion
## Python transfomrations in dbt Cloud 
Duration: 2
```

2023-05-30 12:13 UTC, amychen1776 commented on site/sfguides/src/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python.md
> +<!-- ### Covariate encoding
```suggestion
<!-- ### Covariate encoding
Duration: 5
```

2023-05-30 12:14 UTC, amychen1776 commented on site/sfguides/src/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python.md
> +## Machine Learning: training and prediction
```suggestion
## Machine Learning: training and prediction
Duration: 1
```

2023-05-30 12:16 UTC, amychen1776 commented on site/sfguides/src/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python.md
> +## Pipeline Deployment
```suggestion
## Pipeline Deployment 
Duration: 5
```

2023-05-30 12:16 UTC, amychen1776 commented on site/sfguides/src/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python.md
> +## Conclusion
```suggestion
## Conclusion
Duration: 1
```

2023-05-30 12:17 UTC, amychen1776 commented on site/sfguides/src/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python.md
> +<!-- TODO WORKSHOP WILL NOW PICK UP FROM HERE AFTER FIRST PYTHON MODEL! -->
Can we remove all the quoted out text?

2023-05-30 13:06 UTC, HopeMWatson commented
Hi Amy,

Since we cut out significant sections to cut down on time, I commented
these out. Similar to a "hidden slide".
We can definitely delete these out, but I'm going to need to save the
content and move it into a separate holding repo so I can go back and
update the dbt docs website with these steps.

Best,
Hope

(p) +1 610-906-5294
(e) ***@***.***



On Tue, May 30, 2023 at 8:17 AM Amy Chen ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> site/sfguides/src/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python/leverage_dbt_cloud_to_generate_ml_ready_pipelines_using_snowpark_python.md
> <https://github.com/Snowflake-Labs/sfquickstarts/pull/679#discussion_r1210186886>
> :
>
> > +        # filter the data based on the specified year
> +        hold_out_dataset =  encoding.loc[encoding['RACE_YEAR'] == year]
> +
> +        return hold_out_dataset
> +    ```
> +3. Execute the following in the command bar:
> +    ```bash
> +    dbt run --select training_and_testing_dataset hold_out_dataset_for_prediction
> +    ```
> +    To run multiple models by name, we can use the *space* syntax [syntax](/reference/node-selection/syntax) between the model names.
> +4. **Commit and sync** our changes to keep saving our work as we go using `ml data prep and splits` before moving on.
> +
> +👏 Now that we’ve finished our machine learning prep work we can move onto the fun part &mdash; training and prediction! -->
> +
> +<!-- ------------------------ -->
> +<!-- TODO WORKSHOP WILL NOW PICK UP FROM HERE AFTER FIRST PYTHON MODEL! -->
>
> Can we remove all the quoted out text?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Snowflake-Labs/sfquickstarts/pull/679#pullrequestreview-1450802067>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJTGRKVKXBAZH4TEXR45DADXIXQPJANCNFSM6AAAAAAYO5APOA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-01 18:56 UTC, hope-wat commented
All requested changes have been made for durations and deletion of commented areas. Found under fe774f9. 
Estimated time now read 65 minutes. 

<img width="1912" alt="Screenshot 2023-06-01 at 2 50 03 PM" src="https://github.com/Snowflake-Labs/sfquickstarts/assets/111770816/3da59ac2-e874-4de5-b16b-4222c23a46a6">

2023-06-02 16:14 UTC, merged