new NLP and ML Quickstarts with Snowpark and Streamlit submission
Snowflake-Labs/sfquickstarts pull request #691
Opened 2023-06-05 19:43 UTC by sfc-gh-imehaddi

2023-06-05 19:45 UTC, sfc-gh-ghernandez commented
@iamontheinet Can you take a look at this Quickstart by @sfc-gh-imehaddi please? This is a candidate for the demo program too (in time for Summit). Thank you.

2023-06-07 17:03 UTC, sfc-gh-ghernandez requested changes
Hi @sfc-gh-imehaddi – I requested some very minor changes, and also left some comments where you should update things in the entire .md file. @iamontheinet may have more comments, but on my end, that is all I had for now. Thank you again for submitting!!

2023-06-07 17:03 UTC, sfc-gh-ghernandez commented on site/sfguides/src/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis.md
> +# End to End NLP and ML using Snowpark Python and Streamlit: Sentiments Analysis
```suggestion
NLP and ML with Snowpark Python and Streamlit for Sentiment Analysis
```

2023-06-07 17:03 UTC, sfc-gh-ghernandez commented on site/sfguides/src/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis.md
> +This quickstarts is showing how we can do Natural Language Processing (NLP) and ML within 100% Snowflake using Snowpark Python ans Streamlit as well. Our use case is about doing : Sentiment Analysis
```suggestion
This Quickstart will demonstrate how you can perform Natural Language Processing (NLP) and ML within Snowflake using Snowpark Python and Streamlit. We'll use these tools to perform sentiment analysis with Snowpark (feature engineering, training, and prediction).
```

2023-06-07 17:03 UTC, sfc-gh-ghernandez commented on site/sfguides/src/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis.md
> +- A Snowflake Account with ACCOUNTADMIN role. If you do'nt have one, you can register for a [free trial account](https://signup.snowflake.com/) Account
```suggestion
- A Snowflake Account with ACCOUNTADMIN role. If you don't have one, you can register for a [free trial account](https://signup.snowflake.com/)
```

2023-06-07 17:03 UTC, sfc-gh-ghernandez commented on site/sfguides/src/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis.md
> +Create conda environment. Let's name the environment nlp_ml_sentiment_analysis.
```suggestion
Create a conda environment. Let's name the environment nlp_ml_sentiment_analysis.
```

2023-06-07 17:03 UTC, sfc-gh-ghernandez commented on site/sfguides/src/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis.md
> +Update the Snowflake connexion file : connection.json
```suggestion
Update the Snowflake connection file: connection.json
```

2023-06-07 17:03 UTC, sfc-gh-ghernandez commented on site/sfguides/src/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis.md
> +### Activate Python environment using conda :
```suggestion
### Activate Python environment using conda
```

2023-06-07 17:03 UTC, sfc-gh-ghernandez commented on site/sfguides/src/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis.md
> +### Run Streamlit App :
```suggestion
### Run Streamlit App
```

2023-06-07 17:03 UTC, sfc-gh-ghernandez commented on site/sfguides/src/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis.md
> +### Option 1 - Automatically : with Streamlit App
```suggestion
### Option 1 - Environment setup via the Streamlit App
```

2023-06-07 17:03 UTC, sfc-gh-ghernandez commented on site/sfguides/src/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis.md
> +![Puppy](./assets/Setup_Snowflake_Objects.png)
Update all instances of "Puppy" in here to a proper description of the image. This is for visually impaired users who use screen readers to navigate the internet.

2023-06-07 17:03 UTC, sfc-gh-ghernandez commented on site/sfguides/src/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis.md
> +![Puppy](./assets/Setup_Snowflake_Objects_Results.png)
Update all instances of "Puppy" in here to a proper description of the image. This is for visually impaired users who use screen readers to navigate the internet.

2023-06-07 17:03 UTC, sfc-gh-ghernandez commented on site/sfguides/src/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis.md
> +![Puppy](./assets/DB_IMDB.png)
Update all instances of "Puppy" in here to a proper description of the image. This is for visually impaired users who use screen readers to navigate the internet.

2023-06-07 17:03 UTC, sfc-gh-ghernandez commented on site/sfguides/src/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis.md
> +### Option 2 - Manually : with Snowsight
```suggestion
### Option 2 - Environment setup via Snowsight
```

2023-06-07 17:03 UTC, sfc-gh-ghernandez commented on site/sfguides/src/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis.md
> +Then, run the following SQL commands to create the DATABASE :
```suggestion
Then, run the following SQL commands to create the database:
```

2023-06-07 17:03 UTC, sfc-gh-ghernandez commented on site/sfguides/src/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis.md
> +Run the following SQL commands to create the TABLES :
```suggestion
Run the following SQL commands to create the tables:
```

2023-06-07 17:03 UTC, sfc-gh-ghernandez commented on site/sfguides/src/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis.md
> +Run the following SQL commands to create the WAREHOUSE :
```suggestion
Run the following SQL commands to create the warehouse:
```

2023-06-07 17:03 UTC, sfc-gh-ghernandez commented on site/sfguides/src/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis.md
> +Run the following SQL commands to create the STAGE :
```suggestion
Run the following SQL commands to create the stage:
```

2023-06-07 17:03 UTC, sfc-gh-ghernandez commented on site/sfguides/src/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis.md
> +We used Python code to load the data into Snowflake. In order to simplify code execution you can click on the right button to start loading the data.
Which button does "right button" refer to? I was trying to locate it via the screenshot, but did not know which one you were referring to.

2023-06-07 17:03 UTC, sfc-gh-ghernandez commented on site/sfguides/src/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis.md
> +Use use the section **Analyze** to explore and analyze the datasets and see some metrics.
```suggestion
Use the section **Analyze** to explore and analyze the datasets and see some metrics.
```

2023-06-07 17:03 UTC, sfc-gh-ghernandez commented on site/sfguides/src/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis.md
> +![Puppy](./assets/Analyze_Data1.png)
Same comment about "Puppy", and for all instances below.

2023-06-07 17:03 UTC, sfc-gh-ghernandez commented on site/sfguides/src/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis.md
> +Choose the dataset that you want to analyze :
A space is not needed between the final word of the statement and `:`. Can you please update this in the entire file?

```suggestion
Choose the dataset that you want to analyze:
```

2023-06-07 17:03 UTC, sfc-gh-ghernandez commented on site/sfguides/src/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis.md
> +### What You'll Learn :
You don't need a `:` at the end of section titles (i.e. titles that start with `#`, `##`, etc,), so you can remove from here and rest of file.

2023-06-07 17:03 UTC, sfc-gh-ghernandez commented on site/sfguides/src/end_to_end_nlp_and_ml_using_snowpark_python_and_streamlit:_sentiments_analysis/assets/SAMPLE.jpg
You can delete this file, just to make the overall PR smaller.

2023-06-08 07:46 UTC, sfc-gh-imehaddi commented
@iamontheinet Can you merge and deploy this please? Cc @sfc-gh-ghernandez

2023-06-08 07:48 UTC, sfc-gh-imehaddi commented
@iamontheinet Can you please check and merge this please? Cc @sfc-gh-ghernandez

2023-06-15 16:03 UTC, sfc-gh-imehaddi reviewed
Update following feedbacks. @iamontheinet

2023-06-15 16:34 UTC, sfc-gh-imehaddi commented
No title on Dash side even if it's run locally

2023-06-15 16:34 UTC, closed without merging